# ॐ तारे तुत्तारे तुरे स्वाहा - Netlify Configuration for Six Perfections
# Protected by Green Tara's swift action 💚

[build]
  # Build directory for the web application (now in root)
  publish = "dist"
  
  # Build command for the frontend (now in root)
  command = "npm install && npm run build"
  
  # Node.js version
  environment = { NODE_VERSION = "18" }

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# 🙏 Six Perfections API Functions (Serverless)
[functions]
  directory = "netlify/functions"
  
# 💎 Environment variables for Pure JSON Architecture
[context.production.environment]
  NODE_ENV = "production"
  JWT_SECRET = "six_perfections_diamond_mind_production_secret_2024"
  DATA_DIR = "/tmp/six_perfections_data"
  USE_JSON_STORAGE = "true"

[context.development.environment]
  NODE_ENV = "development"
  JWT_SECRET = "six_perfections_diamond_mind_dev_secret"
  DATA_DIR = "/tmp/six_perfections_data"
  USE_JSON_STORAGE = "true"

# 📿 Redirects for SPA routing and API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 🛡️ Headers for security (Mahakala's protection)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# 💊 Health check redirect
[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

# 📱 Progressive Web App support
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"

# 🌟 Cache static assets (dharma is eternal)
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 